name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # run tests with -trimpath to hopefully share cache between gosim
      # invocations in different folders
      - name: Test
        run: GOFLAGS=-trimpath ./test.sh --concurrency 1
